apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2024-05-14T06:59:20Z","labels":{"app":"spring-petclinic-rest"},"name":"spring-petclinic-rest","namespace":"default","resourceVersion":"2706","uid":"9a513001-aa62-4962-ab67-a3a45a73bca7"},"spec":{"allocateLoadBalancerNodePorts":true,"clusterIP":"10.110.232.238","clusterIPs":["10.110.232.238"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"nodePort":30396,"port":9966,"protocol":"TCP","targetPort":9966}],"selector":{"app":"spring-petclinic-rest"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2024-05-14T07:19:32Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "475"
  uid: 36099981-0378-4374-b2b6-67173ed0ba4a
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.110.232.238
  clusterIPs:
  - 10.110.232.238
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30396
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
