apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-16T06:47:06Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "441"
  uid: 450dfca1-c7bf-43d3-b112-b16e97db102b
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.103.125.18
  clusterIPs:
  - 10.103.125.18
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32147
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
